### ISSUE TITLE
downloading broken

### ISSUE THREAD

**Issue by csbrown** [MIT-LCP/wfdb-python#109]
python 3.5.2, ubuntu 16.04

symptoms:

```
>>> wfdb.io.dl_database("capslpdb", "blah")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/wfdb/io/record.py", line 1365, in dl_database
    r = requests.get(dburl)
NameError: name 'dburl' is not defined
```

workaround:

```
>>> wfdb.io.record.dburl = "https://www.physionet.org/physiobank/database" #monkey patch
```

**Comment by cx1111** [comment]
Uploaded change to pypi.
