### ISSUE TITLE
plt.show() takes no arguments

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [MIT-LCP/wfdb-python#144]
There is an error in line 120 of plot.py

https://github.com/MIT-LCP/wfdb-python/blob/70b12f6d3507e87d63599f013279dadf07838d0b/wfdb/plot/plot.py#L120

This needs to read `plt.show()` without argument. While previously useless arguments were ignored, in the newest version of matplotlib this *might* throw an error (depending on which backend is in use).

**Comment by sumuzhao** [comment]
Hey, I always got this error. Do you know what it means and how I can solve it? Thanks a lot!
Traceback (most recent call last):
  File "/Users/sumuzhao/ETHZ/Semester_project_2/edb/Test1.py", line 12, in <module>
    wfdb.plot_wfdb(record=record, annotation=ann, title='EDB 0103', time_units='seconds')
  File "/Users/sumuzhao/anaconda3/python.app/Contents/lib/python3.6/site-packages/wfdb/plot/plot.py", line 414, in plot_wfdb
    figsize=figsize, return_fig=return_fig)
  File "/Users/sumuzhao/anaconda3/python.app/Contents/lib/python3.6/site-packages/wfdb/plot/plot.py", line 120, in plot_items
    plt.show(fig)
  File "/Users/sumuzhao/anaconda3/python.app/Contents/lib/python3.6/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
TypeError: __call__() takes 1 positional argument but 2 were given

**Comment by davidsalb** [comment]
Answered [here] (https://stackoverflow.com/questions/52520877/the-wfdb-plot-demo-results-in-typeerror)
Until this is fixed you may change line 120 at your local package `wfdb/plot/plot.py` where it needs to be `plt.show()` instead of `plt.show(fig)`. You probably need to change the file permission before you can edit it.

**Comment by sumuzhao** [comment]
@davidsalb Thanks a lot! It works!
