### ISSUE TITLE
dl_database fails with requests.exceptions.ConnectionError (Connection refused)

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/wfdb-python#174]
Two tests are currently failing with a connection error:

```
======================================================================
ERROR: test_record.TestDownload.test_dl_database_no_dat_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tompollard/projects/wfdb-python/tests/test_record.py", line 586, in test_dl_database_no_dat_file
    wfdb.dl_database('afdb', './download-tests/', ['00735'])
  File "/Users/tompollard/projects/wfdb-python/wfdb/io/record.py", line 1611, in dl_database
    r = requests.get(db_url)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='physionet.org', port=8080): Max retries exceeded with url: /physiobank/database/afdb/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x121b8af98>: Failed to establish a new connection: [Errno 61] Connection refused'))
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): physionet.org:80
urllib3.connectionpool: DEBUG: http://physionet.org:80 "GET /physiobank/database/afdb HTTP/1.1" 301 185
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): physionet.org:8080
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_record.TestDownload.test_dl_database_with_dat_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tompollard/projects/wfdb-python/tests/test_record.py", line 590, in test_dl_database_with_dat_file
    wfdb.dl_database('afdb', './download-tests/', ['04015'])
  File "/Users/tompollard/projects/wfdb-python/wfdb/io/record.py", line 1611, in dl_database
    r = requests.get(db_url)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='physionet.org', port=8080): Max retries exceeded with url: /physiobank/database/afdb/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x121b470f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): physionet.org:80
urllib3.connectionpool: DEBUG: http://physionet.org:80 "GET /physiobank/database/afdb HTTP/1.1" 301 185
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): physionet.org:8080
--------------------- >> end captured logging << ---------------------
```

**Comment by tompollard** [comment]
Works fine if the source is switched to the development site: `PB_INDEX_URL = 'http://alpha.physionet.org/physiobank/database/'`

**Comment by bemoody** [comment]
So, the first problem is that you're requesting
<http://physionet.org/physiobank/database/afdb> when you should be
requesting <http://physionet.org/physiobank/database/afdb/>.

Server should be fixed now though.

**Comment by tompollard** [comment]
Great, thanks Benjamin. I'll look at updating the request URL.

**Comment by Lucas-Mc** [comment]
I think this may be similar to #166 .
