### ISSUE TITLE
rdann annotation test intermittently fails

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/wfdb-python#18]
In Python 2, [test_rdann](https://github.com/MIT-LCP/wfdb-python/blob/master/tests/test_readannot.py) sometimes passes:

```bash
$ nosetests
----------------------------------------------------------------------
Ran 14 tests in 4.008s

OK
```

... and sometimes fails. The error appears to be consistently the 3rd item in the `comp` list, sometimes in test_1 and sometimes in test_2:

```bash
$ nosetests
======================================================================
FAIL: test_readannot.test_rdann.test_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tompollard/projects/wfdb-python/tests/test_readannot.py", line 104, in test_2
    assert (comp == [True] * 6)
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
print comp
[True, True, False, True, True, True]
--------------------- >> end captured stdout << ----------------------
----------------------------------------------------------------------
Ran 14 tests in 3.987s

FAILED (failures=1)

```

**Comment by tompollard** [comment]
The failure is in the comparison between subtype and Tsubtype (target subtype), which should be equal. In subtype, sometimes the value -9223372036854775808 appears instead of 0. For example:

```python
subtype = [0, -9223372036854775808, 0, 0, -9223372036854775808, 0,
           0, 0, 0, -9223372036854775808, -9223372036854775808, 0,
           0, 0, -9223372036854775808, 0, 0, 0, 0, -9223372036854775808, 
           -9223372036854775808, 0]
```

vs: 
```python
Tsubtype = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

**Comment by tompollard** [comment]
> "The number 9,223,372,036,854,775,807, equivalent to the hexadecimal value 7FFF,FFFF,FFFF,FFFF16, is the maximum value for a 64-bit signed integer in computing. It is therefore the maximum value for a variable declared as a long integer (long, long long int, or bigint) in many programming languages running on modern computers. The presence of the value may reflect an error, overflow condition, or missing value."

**Comment by tompollard** [comment]
> "PayPal error
An error in the PayPal payment system in July 2013 accidentally credited $92 quadrillion to the account of Chris Reynolds. (The exact amount credited was US$92,233,720,368,547,940.25 to a final balance of US$92,233,720,368,547,800.00.) PayPal corrected the error, and offered to make a donation to a charity of Reynolds' choice.[1]"

:)
