### ISSUE TITLE
UnicodeDecodeError: rdheader, rdrecord, rdsamp

### ISSUE THREAD

**Issue by maksteel** [MIT-LCP/wfdb-python#219]
When I am trying to read a header and/or signal file with WFDB package in python it throws UnicodeDecodeError. The same file can be read by the command line utility.

```
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wfdb
>>> wfdb.__version__
'2.2.1'
>>> record = wfdb.rdheader("Traces")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 991, in rdheader
    dir_name, pb_dir)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/_header.py", line 710, in _read_header_lines
    for line in fp:
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 2067: invalid start byte
>>> 
```

```
$ wfdbdesc Traces
Record Traces
Starting time: [hh:mm:ss.000 dd/mm/yyyy]
Length:  8:11:16.000 (29476 sample intervals)
Sampling frequency: 1 Hz
40 signals
Group 0, Signal 0:
 File: Traces.dat
 Description: R EMG
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -28931
Group 0, Signal 1:
 File: Traces.dat
 Description: EKG
 Gain: 8.1964834692 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -16093
Group 0, Signal 2:
 File: Traces.dat
 Description: Nasal Pressure
 Gain: 11.3335915936 adu/u
 Initial value: 0
 Storage format: 16 (100 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -21382
Group 0, Signal 3:
 File: Traces.dat
 Description: EMG Diaphram
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 9693
Group 0, Signal 4:
 File: Traces.dat
 Description: L EMG
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -28377
Group 0, Signal 5:
 File: Traces.dat
 Description: Snore
 Gain: 4098.23660885 adu/m
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 0
 Checksum: 5218
Group 0, Signal 6:
 File: Traces.dat
 Description: M1
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 26085
Group 0, Signal 7:
 File: Traces.dat
 Description: C3
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -17017
Group 0, Signal 8:
 File: Traces.dat
 Description: M2
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 6494
Group 0, Signal 9:
 File: Traces.dat
 Description: C4
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -13130
Group 0, Signal 10:
 File: Traces.dat
 Description: O2
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -8748
Group 0, Signal 11:
 File: Traces.dat
 Description: E1
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -18052
Group 0, Signal 12:
 File: Traces.dat
 Description: E2
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -21481
Group 0, Signal 13:
 File: Traces.dat
 Description: O1
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 24071
Group 0, Signal 14:
 File: Traces.dat
 Description: ChinA
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -19424
Group 0, Signal 15:
 File: Traces.dat
 Description: ChinR
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 2622
Group 0, Signal 16:
 File: Traces.dat
 Description: ChinL
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -19587
Group 0, Signal 17:
 File: Traces.dat
 Description: F3
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 11250
Group 0, Signal 18:
 File: Traces.dat
 Description: Thorax
 Gain: 8.1964834692 adu/u
 Initial value: -7588
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 29284
Group 0, Signal 19:
 File: Traces.dat
 Description: Abdomen
 Gain: 8.1964834692 adu/u
 Initial value: -6493
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 32442
Group 0, Signal 20:
 File: Traces.dat
 Description: Thermistor
 Gain: 2976.11262489 adu/m
 Initial value: 0
 Storage format: 16 (100 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 0
 Checksum: -8330
Group 0, Signal 21:
 File: Traces.dat
 Description: Position
 Gain: 6553.4 adu/mV
 Initial value: 6553
 Storage format: 16 (10 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -1489
Group 0, Signal 22:
 File: Traces.dat
 Description: F4
 Gain: 10.8692551374 adu/uV
 Initial value: 0
 Storage format: 16 (500 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 21771
Group 0, Signal 23:
 File: Traces.dat
 Description: CPAP Pressure
 Gain: 3355.36656922 adu/cmH2O
 Initial value: 0
 Storage format: 16 (200 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -278
Group 0, Signal 24:
 File: Traces.dat
 Description: CPAP Flow
 Gain: 301.780270586 adu/l/min
 Initial value: 0
 Storage format: 16 (200 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 11443
Group 0, Signal 25:
 File: Traces.dat
 Description: CPAP Leak
 Gain: 367.157001161 adu/l/min
 Initial value: 0
 Storage format: 16 (200 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 12079
Group 0, Signal 26:
 File: Traces.dat
 Description: SpO2
 Gain: 1 adu/%
 Initial value: 0
 Storage format: 16 (10 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -22592
Group 0, Signal 27:
 File: Traces.dat
 Description: SpO2 BB
 Gain: 1 adu/%
 Initial value: 0
 Storage format: 16 (10 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 7421
Group 0, Signal 28:
 File: Traces.dat
 Description: Plethysmogram
 Gain: 1 adu/mV
 Initial value: 0
 Storage format: 16 (100 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 2867
Group 0, Signal 29:
 File: Traces.dat
 Description: Pulse
 Gain: 1 adu/bpm
 Initial value: 0
 Storage format: 16 (25 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 16901
Group 0, Signal 30:
 File: Traces.dat
 Description: RD-Quality
 Gain: 1 adu/mV
 Initial value: 0
 Storage format: 16 (100 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 12196
Group 0, Signal 31:
 File: Traces.dat
 Description: Heart Rate_DR
 Gain: 107.400038677 adu/bpm
 Initial value: 0
 Storage format: 16
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -18482
Group 0, Signal 32:
 File: Traces.dat
 Description: SpO2-Quality_DR
 Gain: 1 adu/mV
 Initial value: 0
 Storage format: 16 (10 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -10974
Group 0, Signal 33:
 File: Traces.dat
 Description: Flow_DR
 Gain: 66.1919479627 adu/m
 Initial value: 0
 Storage format: 16 (100 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 21939
Group 0, Signal 34:
 File: Traces.dat
 Description: Phase_DR
 Gain: 182.040911566 adu/�
 Initial value: 7
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -31181
Group 0, Signal 35:
 File: Traces.dat
 Description: RMI_DR
 Gain: 376.306051996 adu/�
 Initial value: 32
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -19243
Group 0, Signal 36:
 File: Traces.dat
 Description: RR_DR
 Gain: 373.452685014 adu/cpm
 Initial value: 0
 Storage format: 16
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: -6243
Group 0, Signal 37:
 File: Traces.dat
 Description: XSum_DR
 Gain: 819.000962296 adu/m
 Initial value: -1407
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 0
 Checksum: 5780
Group 0, Signal 38:
 File: Traces.dat
 Description: Tidal Volume_DR
 Gain: 570.671719643 adu/m
 Initial value: 975
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 13461
Group 0, Signal 39:
 File: Traces.dat
 Description: XFlow_DR
 Gain: 818.976398223 adu/m
 Initial value: 14299
 Storage format: 16 (50 samples per frame)
 I/O: can be unbuffered
 ADC resolution: 15 bits
 ADC zero: 0
 Baseline: 1
 Checksum: 7486
```

**Comment by Lucas-Mc** [comment]
This seems like a problem specific to the "Traces" files, probably that the file is in an unexpected encoding. I think I know how this could be fixed though I can't be sure without the actual files. In the issue description you mention `rerecord` and `revamp` as well though these are not provided in the code snippet... do these functions not work either? Is there a way you could share the files giving you issues?

**Comment by maksteel** [comment]
Yes probably, however the `Traces.dat` file was created from `Traces.edf` using `edf2mit` binary https://github.com/MIT-LCP/wfdb-python/issues/87#issuecomment-515311941. I am afraid that the file cannot be shared in its current form. I can install the dev version and try your suggestions if that helps?

```
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wfdb
>>> wfdb.__version__
'2.2.1'
>>> record = wfdb.rdrecord("Traces")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 1154, in rdrecord
    record = rdheader(record_name, pb_dir=pb_dir, rd_segments=False)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 991, in rdheader
    dir_name, pb_dir)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/_header.py", line 710, in _read_header_lines
    for line in fp:
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 2067: invalid start byte
>>> record = wfdb.rdsamp("Traces")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 1394, in rdsamp
    warn_empty=warn_empty)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 1154, in rdrecord
    record = rdheader(record_name, pb_dir=pb_dir, rd_segments=False)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/record.py", line 991, in rdheader
    dir_name, pb_dir)
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/site-packages/wfdb/io/_header.py", line 710, in _read_header_lines
    for line in fp:
  File "/home/mkukreja/.pyenv/versions/anaconda3-2019.10/envs/test-env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 2067: invalid start byte
>>> 
```

Also, when I try to query what type of coding `Traces.dat` is encoded with, it seems there are some characters which are not encoded with `utf-8` 

```
>>> from bs4 import UnicodeDammit
>>> with open('Traces.dat', 'rb') as file:
...   content = file.read()
...
>>> suggestion = UnicodeDammit(content)
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
>>> suggestion.original_encoding
'utf-8'
>>> suggestion.tried_encodings
[('utf-8', 'strict'), ('windows-1252', 'strict'), ('utf-8', 'replace')]
>>>
```

**Comment by Lucas-Mc** [comment]
That is interesting.. I tried the `UnicodeDammit` code-block with a file that was working locally and I got the same results which means something else is probably going on. Can you try this file [here](https://physionet.org/content/sleep-edfx/1.0.0/sleep-telemetry/ST7011J0-PSG.edf)? This one worked locally for me and if it doesn't for you then maybe it's an OS problem since it looks like you are using Linux and I'm using OSX. Probably something else though! Hope this gets us closer!

**Comment by alistairewj** [comment]
Looks like signals 34/35 have an unrecognized character in the gain - could be units of microvolts documented using `μ` or `µ` and the package fails to parse it as UTF-8. @maksteel could you upload a snippet of Traces with maybe 1-2 seconds of data? Particularly the two signals mentioned.

@bemoody do you know if the WFDB C package assumes UTF-8 encoding in the header files?

**Comment by maksteel** [comment]
@alistairewj you are correct about the signal 34/35 units. I edited the EDF header (using just `vim`) then converted it (using `edf2mit`) now it opens correctly in `python`. Can we add a parameter in `rdheader()` to ignore non-utf-8 chars?

Before editing the header in `vim`:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/6572855/83098686-69c76000-a0ff-11ea-9da4-534dc75f7b99.png">

After replacing unknown chars in physical dimensions to 'u':
<img width="920" alt="image" src="https://user-images.githubusercontent.com/6572855/83098850-d3476e80-a0ff-11ea-9a6c-a191112b4c0e.png">

```
$ python
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wfdb
>>> wfdb.__version__
'2.2.1'
>>> sig = wfdb.rdrecord("Traces")
>>> sig.units[34]
'u'
>>> sig.units[35]
'u'
```
>>>

**Comment by Lucas-Mc** [comment]
I'll manually edit one of the existing EDF files to include a unit like that to try and reproduce the issue since we can't upload EDF files here. I'll make a pull request and reference this issue here once I finish it.. I'm thinking it's best just to make sure `rdheader` and the other functions seen here can deal with these files without manually having to add a parameter.

**Comment by maksteel** [comment]
Thanks @Lucas-Mc.

https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt

This can help maybe.
