### ISSUE TITLE
WFDB module cant read records

### ISSUE THREAD

**Issue by insung3511** [MIT-LCP/wfdb-python#354]
```python
#!/usr/bin/python
#
# File: rdann.py       I. Henry   March 28 2005
#
# Minimal WFDB annotator reader written in Python, based on rdann.c
# 							   
# Copyright (C) 2005 Isaac C. Henry (ihenry@physionet.org)

import getopt, wfdb, sys

def main(argv):

    # parse the arguments
    try:
        opts, args = getopt.getopt(argv, "hr:a:", ["help"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
# """
# '''    for opt, arg in opts:
#         if opt in ("-h", "--help"):
#             usage()
#             sys.exit()
#         elif opt == '-r':
#             record = arg
#         elif opt == '-a':
#             annotator = arg
# '''
# """
    record = '0001'
    annotator = 'atr'
    
    if len(record) == 0 or len(annotator) == 0:
        usage()
        sys.exit(2)
        
    # set the sampling frequency
    sps = wfdb.sampfreq(record)
    if sps < 0:
        sps = wfdb.WFDB_DEFFREQ
        wfdb.setsampfreq(sps)
            
    # get a new anninfo object
    ai = wfdb.WFDB_Anninfo()
    
    # set ai fields
    ai.name = annotator
    ai.stat = wfdb.WFDB_READ
    
    # open the annotation
    result = wfdb.annopen( record, ai, 1 )
    
    if result < 0:
        usage()
        sys.exit(2)
        
    # get a new annotation object
    annot = wfdb.WFDB_Annotation()
    
    while wfdb.getann(0, annot) == 0:

        # remove first char from aux string, if there is one
        if annot.aux is not None:
            aux = annot.aux[1:]
        else:
            aux = ""
                
        print("%s,%d,%s,%d,%d,%d,%s" % ( \
              wfdb.mstimstr(-annot.time), \
              annot.time, \
              wfdb.annstr(annot.anntyp),
              annot.subtyp,
              annot.chan, \
              annot.num, \
              aux))

    wfdb.wfdbquit()


def usage():
    print("Usage: rdann.py -r record -a annotator")

    
if __name__ == "__main__":
    main(sys.argv[1:])
#!/usr/bin/python
#
# File: rdann.py       I. Henry   March 28 2005
#
# Minimal WFDB annotator reader written in Python, based on rdann.c
# 							   
# Copyright (C) 2005 Isaac C. Henry (ihenry@physionet.org)

import getopt, wfdb, sys

def main(argv):

    # parse the arguments
    try:
        opts, args = getopt.getopt(argv, "hr:a:", ["help"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
# """
# '''    for opt, arg in opts:
#         if opt in ("-h", "--help"):
#             usage()
#             sys.exit()
#         elif opt == '-r':
#             record = arg
#         elif opt == '-a':
#             annotator = arg
# '''
# """
    record = '0001'
    annotator = 'atr'
    
    if len(record) == 0 or len(annotator) == 0:
        usage()
        sys.exit(2)
        
    # set the sampling frequency
    sps = wfdb.sampfreq(record)
    if sps < 0:
        sps = wfdb.WFDB_DEFFREQ
        wfdb.setsampfreq(sps)
            
    # get a new anninfo object
    ai = wfdb.WFDB_Anninfo()
    
    # set ai fields
    ai.name = annotator
    ai.stat = wfdb.WFDB_READ
    
    # open the annotation
    result = wfdb.annopen( record, ai, 1 )
    
    if result < 0:
        usage()
        sys.exit(2)
        
    # get a new annotation object
    annot = wfdb.WFDB_Annotation()
    
    while wfdb.getann(0, annot) == 0:

        # remove first char from aux string, if there is one
        if annot.aux is not None:
            aux = annot.aux[1:]
        else:
            aux = ""
                
        print("%s,%d,%s,%d,%d,%d,%s" % ( \
              wfdb.mstimstr(-annot.time), \
              annot.time, \
              wfdb.annstr(annot.anntyp),
              annot.subtyp,
              annot.chan, \
              annot.num, \
              aux))

    wfdb.wfdbquit()


def usage():
    print("Usage: rdann.py -r record -a annotator")

    
if __name__ == "__main__":
    main(sys.argv[1:])
```
Here is the code from <a href="https://www.physionet.org/files/wfdb-swig/1.0.0/examples/rdann.py">here</a>. And edit some code here is the error.
```
Traceback (most recent call last):
  File "/Users/bahk_insung/SHIT_OR_FUCK/FUCK-Develop/dbn-ecg/data/unify/offical_rdann.py", line 85, in <module>
    main(sys.argv[1:])
  File "/Users/bahk_insung/SHIT_OR_FUCK/FUCK-Develop/dbn-ecg/data/unify/offical_rdann.py", line 38, in main
    sps = wfdb.sampfreq(record)
AttributeError: module 'wfdb' has no attribute 'sampfreq'
```
I think wfdb module cant read my record. Additionally source code and record are some directory. thanks :D

**Comment by cx1111** [comment]
Where is this script from? It looks like a lot of these functions don't exist in this package, such as `wfdb.mstimstr`

**Comment by insung3511** [comment]
I dont remember where I copied
