### ISSUE TITLE
dldatabase fails to download nested databases correctly

### ISSUE THREAD

**Issue by hcmturner** [MIT-LCP/wfdb-python#46]
In the MIMIC 2 Waveform Database the database is organised in a nested manner, such that directories contain directories which then contain the signal files. Each of these directories has a RECORDS file.

When attempting to download part of this database as follows:
`import wfdb`
`wfdb.dldatabase('mimic2wdb/30', os.getcwd())`

The following error occurs:
`>>> wfdb.dldatabase('mimic2wdb/30',os.getcwd())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/ht1013/.local/lib/python3.5/site-packages/wfdb/records.py", line 1176, in dldatabase
    record = rdheader(baserecname, pbdir = posixpath.join(pbdb, dirname))
  File "/homes/ht1013/.local/lib/python3.5/site-packages/wfdb/records.py", line 851, in rdheader
    headerlines, commentlines = _headers.getheaderlines(recordname, pbdir)
  File "/homes/ht1013/.local/lib/python3.5/site-packages/wfdb/_headers.py", line 413, in getheaderlines
    headerlines, commentlines = downloads.streamheader(recordname, pbdir)
  File "/homes/ht1013/.local/lib/python3.5/site-packages/wfdb/downloads.py", line 15, in streamheader
    r.raise_for_status()
  File "/homes/ht1013/.local/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/mimic2wdb/30/3000003/.hea`

I believe this is because as the directories are listed in the RECORDS file it attempt to find the header files for these, as opposed to entering the directories and looking for records within.

Similar errors occur for attempting other parts or the entire database:
`wfdb.dldatabase('mimic2wdb',os.getcwd())`

**Comment by yf704475209** [comment]
I meet the same question. Could you please tell me how to solve it?

**Comment by oscaratnc** [comment]
I downloaded from the mimic3db  selecting the folders within 30/ that i needed

**Comment by jazzman37** [comment]
wget  -r -np -nH --cut-dirs=2 -R "index.html*" -e robots=off "http://physionet.org/physiobank/database/mimic2wdb"
