### ISSUE TITLE
Error when loading 'f2o01' from database 'fantasia'

### ISSUE THREAD

**Issue by Gijom** [MIT-LCP/wfdb-python#66]
Hello,

when using the command
`signals, fields = wfdb.srdsamp('f2o01', pbdir='fantasia')`

I get the error
```
File "C:\Users\XXX\AppData\Local\Continuum\Miniconda2\lib\site-packages\wfdb\readwrite\_signals.py", line 841, in bytes2samples
    sig[0::2] = sigbytes[0::3] + 256 * np.bitwise_and(sigbytes[1::3], 0x0f)

ValueError: operands could not be broadcast together with shapes (2629214,) (2629213,)
```

Indeed the line above is reached while sigbytes is of even length and in this case sigbytes[1::3] will be of odd length while sig[0::3] will be of even length. This does not match. Not sure what is going on and why it occurs only for this file.

**Comment by cx1111** [comment]
Dat file had fewer bytes than the header specified. I removed 1 sample off the header siglen and recalculated the checksums. Thanks for spotting this.

**Comment by Gijom** [comment]
Many thanks to you !

**Comment by Gijom** [comment]
Hello, not sure if I should post under this closed issue or a open a new one. I first try there. I noticed that many other records where corrupted in the fantasia DB. The corrupted records are:
`[f1y06, f2o03, f2o04, f2o05, f2o08, f2o09, f2o10, f2y05, f2y06, f2y07, f2y08]`

**Comment by cx1111** [comment]
I've fixed those on the standby physionet server. The changes will appear tomorrow. Thanks for pointing them out.

**Comment by Gijom** [comment]
Thanks for your help. I will check them soon. You will hear from me only in case of trouble. Thanks again.

**Comment by Gijom** [comment]
Hello, it seems that the same problem is appearing again. I guess that the sever was retablished to an old version. Anyway I again get the same error for f2o01. It is also probably worth checking the other mentionned files as well :+1: 
[f1y06, f2o03, f2o04, f2o05, f2o08, f2o09, f2o10, f2y05, f2y06, f2y07, f2y08]

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\NG6D12A\AppData\Local\Continuum\Miniconda3\lib\site-packages\wfdb\readwrite\records.py", line 1045, in srdsamp
    record = rdsamp(recordname, sampfrom, sampto, channels, True, pbdir, True)
  File "C:\Users\NG6D12A\AppData\Local\Continuum\Miniconda3\lib\site-packages\wfdb\readwrite\records.py", line 820, in rdsamp
    sampfrom, sampto, channels, smoothframes, ignoreskew)
  File "C:\Users\NG6D12A\AppData\Local\Continuum\Miniconda3\lib\site-packages\wfdb\readwrite\_signals.py", line 693, in rdsegment
    siglen, w_byteoffset[fn], w_sampsperframe[fn], w_skew[fn], sampfrom, sampto, smoothframes)[:, r_w_channel[fn]]
  File "C:\Users\NG6D12A\AppData\Local\Continuum\Miniconda3\lib\site-packages\wfdb\readwrite\_signals.py", line 777, in rddat
    sigbytes = bytes2samples(sigbytes, totalprocesssamples, fmt)
  File "C:\Users\NG6D12A\AppData\Local\Continuum\Miniconda3\lib\site-packages\wfdb\readwrite\_signals.py", line 1004, in bytes2samples
    sig[0::2] = sigbytes[0::3] + 256 * np.bitwise_and(sigbytes[1::3], 0x0f)
ValueError: operands could not be broadcast together with shapes (2629214,) (2629213,)

```

**Comment by cx1111** [comment]
I just checked f2o01.hea and .dat on the two servers. There are no differences. Also, I managed to read them.
