### ISSUE TITLE
Cannot install recent version of wfdb with python 3.4

### ISSUE THREAD

**Issue by mfedoten** [MIT-LCP/wfdb-python#96]
When installing wfdb>=3.7 with python 3.4 the following error occurs:

```
Collecting wfdb==1.3.9 (from -r requirements.txt (line 8))
  Using cached wfdb-1.3.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wr45uqnb/wfdb/setup.py", line 19, in <module>
        __version__ = f.read().split()[-1].strip("'")
    TypeError: Type str doesn't support the buffer API
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wr45uqnb/wfdb/
```

More recent versions of Python (>=3.5) installing the package without any problem.

**Comment by cx1111** [comment]
I'm only supporting 2.7 and 3.5+ sorry. Even the latest anaconda uses 3.6.
